ALTER TABLE ADRESSES DROP FOREIGN KEY FK_ADRESSES_ACCOUNTINFO_idAccount
ALTER TABLE ADRESSES DROP FOREIGN KEY FK_ADRESSES_IDENTITYINFO_ID
ALTER TABLE USERS DROP FOREIGN KEY FK_USERS_ACCOUNTINFO_idAccount
ALTER TABLE USERS DROP FOREIGN KEY FK_USERS_USERIDENTITY_ID
ALTER TABLE USERSHISTORY DROP FOREIGN KEY FK_USERSHISTORY_USERHISTORYINFO_USERID
ALTER TABLE ARTICLES DROP FOREIGN KEY FK_ARTICLES_ARTICLESCOMMANDE_IDCOMMANDE
ALTER TABLE COMMANDES DROP FOREIGN KEY FK_COMMANDES_ADRESSEFACTURATION_IDADRESSE
ALTER TABLE COMMANDES DROP FOREIGN KEY FK_COMMANDES_ADRESSEWAREHOUSERETURN_IDADRESSE
ALTER TABLE COMMANDES DROP FOREIGN KEY FK_COMMANDES_ADRESSELIVRAISON_IDADRESSE
ALTER TABLE COMMANDES DROP FOREIGN KEY FK_COMMANDES_ACCOUNTINFO_idAccount
ALTER TABLE WAREHOUSES_ARTICLE_POSITIONS DROP FOREIGN KEY WRHSSARTICLEPOSITIONSRTCLSSTOCKSPOSITIONSIDARTICLE
DROP TABLE ACCOUNTS
DROP TABLE ADRESSES
DROP TABLE PERSONNES
DROP TABLE USERS
DROP TABLE USERSHISTORY
DROP TABLE ARTICLES
DROP TABLE COMMANDES
DROP TABLE ORDER_HISTORY
DROP TABLE WAREHOUSES_ARTICLE_POSITIONS
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
