ALTER TABLE USERS DROP FOREIGN KEY FK_USERS_ACCOUNTINFO_IDACCOUNT
ALTER TABLE USERSHISTORY DROP FOREIGN KEY FK_USERSHISTORY_USERHISTORYINFO_USERID
DROP TABLE ACCOUNTS
DROP TABLE ADRESSES
DROP TABLE USERS
DROP TABLE USERSHISTORY
