CREATE TABLE personne (NOM VARCHAR(255) NOT NULL, PRENOM VARCHAR(255) NOT NULL, AGE INTEGER, ID INTEGER, PRIMARY KEY (NOM, PRENOM))
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT DECIMAL(38), PRIMARY KEY (SEQ_NAME))
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 0)
